INSERT INTO lotgd.races (racename,raceauthor,raceactive,racevillage,racecolour,racechoose,raceset,racenewday,raceturns,racetravel,racepvp,racegrave,newdaybuff,pvpadjust,`alter-gemchance`,creatureencounter,`battle-victory`,`battle-defeat`,module) VALUES
	 ('Oriam','Demonmegi',1,'Village of Avalon','`$','In your past as a `$Oriam`0 , you grew up amidst the simple joys and deep connection with nature, where you learned the art of farming and your roots were firmly anchored.','The Oriam are a simple and down-to-earth people. They were once peaceful farmers who lived in the fertile plains of Avalon. But after the devastating war with the Sha\\''Ahoul, they were faced with unimaginable challenges and hardships.

The battles of the war had ravaged their lands, destroyed their crops, and laid waste to their homes. Many of their family members and beloved friends fell in combat, and the survivors were left to cope with painful loss and grief.

The once-flourishing fields of the Oriam lay fallow and barren. The seeds they had lovingly sown could no longer thrive, as the soil was tainted by the impacts of war and dark magic. The once-idyllic villages were now nothing but ruins, and the people had to live in makeshift shelters as they struggled to rebuild their homeland.

Food shortages became a tormenting reality for the Oriam. Those who were once proud of their harvests now found themselves forced to survive on scarce resources. They had to learn to manage with what little they had and support each other to endure hunger and deprivation.

The war also left deep emotional scars in the hearts of the Oriam. Distrust and fear now governed life within the community. Many feared that the shadow of the Sha\\''Ahoul might descend upon them once again, leading to tension and conflict among themselves.

Despite all these hardships and difficulties, the Oriam did not give up. They were a proud and resilient people, determined to rebuild their homeland and continue their way of life as farmers. They understood that only through unity and collective effort would they have a chance to overcome the challenges and reclaim their way of life.

The hope for a better future drove the Oriam to till their fields once more and restore their villages. Over time, they began to recover from the scars of war and to regain trust in one another.

The story of the Oriam is marked by suffering and loss, but also by strength and determination. They are a people who have learned to face the worst of challenges and to never lose faith in themselves or their homeland.','As a member of a resilient farming race, you gain +1 Round!',1,0,0,0,'a:4:{s:4:"name";s:29:"`$ Farmer `^from the Frontier";s:7:"wearoff";s:62:"Racial Power used up. You will regain it on the next game day.";s:6:"rounds";s:1:"1";s:6:"schema";s:12:"race_creator";}','',0,'','','',NULL),
	 ('Cathea','Demonmegi',1,'Village of Avalon','`@','In your past as a `@Cathea`0, you spent carefree days on the vast meadows, surrounded by gentle cattle and the soothing rhythm of rural life, while the soft rustling of leaves and the chirping of birds filled your soul.','The Cathea are a people who call the vast lands of Avalon home and specialize in livestock breeding. Their close connection to nature and their ability to cultivate the land make them talented animal breeders and farmers.

The Cathea have developed a deep understanding of the needs of their animals and maintain a harmonious relationship with them. Through gentle handling and loving care, the herds under their watch thrive, preserving the balance between humans and animals.

In the green pastures of Avalon, you’ll find the Cathea among their magnificent herds. Their knowledge of the plant world and the natural rhythms of the land enables them to provide the animals with healthy feed and optimize their living conditions.

The Cathea take pride in their skills and view livestock breeding as an art passed down from generation to generation. Their cultural traditions and rituals honor the bond between humans and animals, and they celebrate each new life that is born.

Although the Cathea are generally a peaceful people, they do not hesitate to defend their herds and land with determination when threatened by external dangers. Their skilled animal-handling abilities make them surprisingly capable defenders who protect their herds with passion.

The Cathea live in harmony with nature and cherish the beauty of the landscape around them. Their lifestyle as livestock breeders and their deep understanding of the animal world have made them an important part of life in Avalon, and their bond with the earth and its creatures makes them a fascinating and respected people.','As a member of a livestock-breeding skilled race, you receive 1.25x Defense!',0,0,0,0,'a:5:{s:4:"name";s:40:"`@Livestock Breeder `&from the Highlands";s:7:"wearoff";s:62:"Racial Power used up. You will regain it on the next game day.";s:6:"rounds";s:2:"10";s:6:"defmod";s:4:"1.25";s:6:"schema";s:12:"race_creator";}','',0,'','','',NULL),
	 ('Nisos','Demonmegi',1,'Village of Avalon','`1','In your past as a`1Nisos`0, you spent your youth on the endless seas, surrounded by the salty breeze and the roar of the waves in your ears. In these turbulent waters, you discovered your true passion for gambling, where the thrill of the game quickened your pulse and the prospect of a win filled your mind.','The Nisos are a fascinating people who do not hail from the vast mainland but from a remote and mysterious island. Their culture is rich with traditions and customs developed over centuries, making them a unique part of the world of Eurale.

The Nisos have a special passion for gambling. For them, games of chance and skill are not merely entertainment but a way to connect with the unknown and test their abilities. From simple dice games to complex card games, they have developed a variety of games that make players’ hearts race.

This love of gambling is deeply woven into their culture and is often celebrated during social gatherings and festivities. The excitement and thrill of playing bring together people from diverse backgrounds, creating an atmosphere of community and camaraderie.

But the Nisos are not only masters of gambling—they are also experienced seafarers. Coming from a secluded island, they have developed impressive knowledge of the sea and shipbuilding over the centuries. Their sailboats glide effortlessly over the waves, and their skillful handling of ships makes them respected and sought-after sailors throughout Eurale.

The Nisos share a close connection with the sea and respect the forces of nature. Their seafaring songs and stories tell of adventures and brave discoveries carried across the oceans.

The island culture of the Nisos is marked by a sense of freedom and independence. They have a strong community that sticks together and cares for one another. The harmony between their passion for gambling and their seafaring tradition has made them a fascinating and admirable people who have inspired the imagination of the people in Eurale since time immemorial.','As a member of a race known for their skilled seafarers, you receive a general 5% discount on equipment purchases and 100% of the price back when selling equipment!',0,0,0,0,'a:4:{s:4:"name";s:18:"`1The blue `&Fleet";s:7:"wearoff";s:62:"Racial Power used up. You will regain it on the next game day.";s:6:"rounds";s:2:"10";s:6:"schema";s:12:"race_creator";}','',0,'','','',NULL),
	 ('Ahoul','Demonmegi',1,'Village of Avalon','`q','In your past as an`qAhoul`0 in the vast steppes, you spent carefree days among a powerful society of orc-like warriors. Although you might not have been blessed with the same intellect as the Sha\\''men, you discovered your true strength as an unyielding warrior soul, forming the backbone of the Sha\\''Ahoul army and being unstoppable on the battlefield.','In these seemingly endless steppes exists a race called Ahoul, creature-like beings of impressive orc-like appearance. But the history of the Ahoul is inseparably woven with a fateful connection that shaped their existence.

Long ago, there were two groups in this world: the Sha\\''men, sages with ancient wisdom and mystical powers, and the Ahoul, powerful warriors with impressive physical strength but limited mental abilities. While many may have underestimated them because of their intellectual limitations, their significance should never be undervalued.

It was an unexpected event that brought the turning point—a meeting that would forever change the fate of the two races. One day, the paths of the Sha\\''men and the Ahoul crossed, and an unexpected bond arose between them. This connection awakened a new power, previously unknown: the Sha\\''Ahoul. From this fusion emerged a unique hybrid race that united the best of both worlds.

The Ahoul, now part of the Sha\\''Ahoul, became unyielding warriors on the battlefield. Their physical strength and endurance were legendary, and they served as the true standard-bearers of brute force in the Sha\\''Ahoul army. In the fiercest battles, it was the Ahoul who advanced as an unstoppable force and defeated their enemies with impressive violence.

Although their intelligence was limited compared to the Sha\\''men, their loyalty and unshakeable determination led the Sha\\''Ahoul as a whole to become even stronger. The sages of the Sha\\''men guided the Ahoul in battles and strategic decisions, and the Ahoul obeyed without hesitation because they knew that together they were unbeatable.

So while the Ahoul may not be blessed with the same intellect as the Sha\\''men, their unwavering fighting spirit, loyalty, and pure, raw strength made them the irreplaceable pillars of Sha\\''Ahoul society. They may be known as the brute force of the army, but their role and significance in the Sha\\''Ahoul world go far beyond that.','As a member of a race known for its brutality in combat, you receive 1.25x attack!',0,0,0,0,'a:5:{s:4:"name";s:16:"`qRugged `hBrute";s:7:"wearoff";s:62:"Racial Power used up. You will regain it on the next game day.";s:6:"rounds";s:2:"10";s:6:"atkmod";s:4:"1.25";s:6:"schema";s:12:"race_creator";}','',0,'','','',NULL),
	 ('Dwarf','Demonmegi',1,'Village of Avalon','`6','In your past as a `6Dwarf`0 , you found yourself of small stature, but you mastered the art of mining and living in the deep caves and grottoes, not always the fastest, but always knowing how to find valuable things.','The dwarf race we are talking about is distinguished by their exceptional craftsmanship, expertise in construction, and especially in mining, including the extraction of gold and gemstones. These dwarves are capable of delving deep into the earth to harvest valuable resources. Their high skill and dedication enable them to create exquisite jewelry, artistic works, and solid structures.

They are based east of the Citadel Avalon and have significantly contributed to building this impressive city. The dwarves were valued for their tireless work and construction skills, which allowed them to create magnificent buildings and fortress-like structures that left a lasting impression.

The dwarves are known for their expertise in handling metals and minerals. Their skillful processing of gemstones, combined with extensive knowledge of metallurgy, enables them to craft unique treasures and items of unparalleled quality. Within their context, these dwarves are often regarded as masters of the underground, as they possess the ability to move through the deepest layers of the earth and discover hidden riches there.

Their mining skills are invaluable, as they can extract precious resources such as gold, silver, and gemstones from the deepest parts of the mountains. These raw materials not only serve as the basis for their wealth but also as trade goods with other races and communities. Over time, these dwarves have created an impressive network of shafts, tunnels, and mines to support their mining activities.

Overall, these dwarves form a significant society valued for their craftsmanship and mining expertise. They play an important role in their respective context, both economically and culturally, and have also contributed substantially to the construction of the magnificent Citadel Avalon.','As a member of a race known for its excellent mining skills, the gemstone find rate after battle is increased from 25% to 50%!',0,0,0,0,'a:4:{s:4:"name";s:32:"`qExpertise `6from the Mountains";s:7:"wearoff";s:62:"Racial Power used up. You will regain it on the next game day.";s:6:"rounds";s:2:"10";s:6:"schema";s:12:"race_creator";}','',50,'','','',NULL),
	 ('Aratoy','Demonmegi',1,'Village of Avalon','`L','In your past as a LAratoy`0, you belonged to a nature-connected people who were native to the forests of Eurale. You mastered the art of archery with impressive precision and followed the wise guidance of the clan mother, who led you and your clan on the path of harmony with nat','The Aratoy are a people who live in the deep forests of Eurale and share a close connection with nature. They are masters of the forest and have perfected the art of living in harmony with their surroundings. With skillful handling of nature, they are able to make the best use of the forest’s resources and apply their knowledge of herbs and plants for healing and well-being.

Their impressive skills as archers are legendary. With precision and grace, they draw their bows and send their arrows flying with deadly accuracy. Their archery prowess is unmatched, allowing them to defeat their enemies from a distance while skillfully disappearing into the depths of the forest.

Unlike other kingdoms in Eurale, where the king holds the highest authority, the Aratoyaner have a unique hierarchy. At the top stands the clan mother, a wise and experienced leader who not only cares for the well-being of the people but also nurtures the connection to nature and the spirit of the forest. The king in their realm holds more of a symbolic role focused on relationships and diplomacy, while actual power rests in the hands of the wise clan mother.

The Aratoyaner live in harmony with nature and respect the mysteries of the forest. They worship the nature spirits and firmly believe in the cycle of life. Their cultural customs and rituals are closely tied to nature, reflecting their deep bond with the environment.

As forest dwellers, the Aratoyaner are skilled hunters and gatherers. They have a profound understanding of the flora and fauna of their land and know how to maintain the ecosystem in balance. Through their wisdom and natural talents, they have become an important part of Eurale, and their people are admired throughout the region for their elegance, bravery, and wisdom.','As a member of a race known for their strong unity, you gain +1 Companion!',0,0,0,0,'a:5:{s:4:"name";s:28:"`LChild of the `&Clan Mother";s:7:"wearoff";s:62:"Racial Power used up. You will regain it on the next game day.";s:6:"rounds";s:2:"10";s:11:"minioncount";s:1:"2";s:6:"schema";s:12:"race_creator";}','',0,'','','',NULL),
	 ('Shaahoul','Demonmegi',1,'Village of Avalon','`q','In your past as a`QSha\\''Ahoul`0, you experienced a diverse world where you developed average warrior qualities and average intelligence, but you also learned that your unique balance of both makes you an important part of this community.','The Sha\\''Ahoul are a unique and fascinating race, born from the union of the Sha\\''Men and Ahoul. As hybrid beings, they inherit both the warrior skills of the Ahoul and the mystical powers of the Sha\\''Men. In their childhood as Sha\\''Ahoul, they grew up in a diverse community where they developed average warrior qualities and average intelligence.

The Sha\\''Ahoul may not be the strongest warriors, nor may their intelligence be outstanding, but they possess a unique balance of both. They are capable fighters on the battlefield, with sufficient mastery of the art of war to assert themselves successfully in conflicts. Their physical strength is respectable, and they can move effectively in the chaos of battle.

As for their intelligence, they may not possess the same level of wisdom and magic as the Sha\\''Men, but they are by no means foolish. Their average intelligence allows them to make strategic decisions and act appropriately in complex situations. They learn from experience and can find solutions to overcome challenges.

As part of a diverse society of Sha\\''Ahoul, they grew up learning that their strengths and weaknesses make them an important part of the community. They have learned to rely on their comrades and work together as a team to face the challenges they encounter.

Although they are neither the best warriors nor the wisest mages, the Sha\\''Ahoul are proud of their unique traits and of having a place in the Sha\\''Ahoul community. They know that through their versatility and adaptability, they play an important role and that when they unite their powers, they can be a mighty force ready to fight for the good of the Sha\\''Ahoul.','As a member of a race that represents balance, you receive 1.25x attack and 1.25x defense!',0,0,0,0,'a:6:{s:4:"name";s:25:"`qBalance of `Qthe Steppe";s:7:"wearoff";s:62:"Racial Power used up. You will regain it on the next game day.";s:6:"rounds";s:2:"10";s:6:"atkmod";s:4:"1.25";s:6:"defmod";s:4:"1.25";s:6:"schema";s:12:"race_creator";}','',0,'','','',NULL),
	 ('Elf','Demonmegi',1,'Village of Avalon','`g','In your past as an `GElf`0, you found yourself in the forests north of Avalon, as a graceful inhabitant of this mystical region. You proved to be a talented archer and master of stealth, but the fragility of your form took its toll.','The Elves are an ancient race that has inhabited the majestic forests north of Avalon since time immemorial. Their grace and beauty are legendary, and their movements resemble a gentle dance through the underbrush. With deep respect and an intimate connection to nature, they cherish everything it offers—from the mighty towering trees to the tiny flowers on the forest floor. This love for nature is also reflected in their lifestyle, for in harmony with the forests, they prefer not to build permanent structures but to adapt to the conditions of nature.

In the heart of the forest, north of Avalon, however, the Elves have established an outpost. From this strategically important location, they are the guardians of the woods and watch over their beloved land. When the threatening union of the Sha\\''Ahoul appeared and posed a danger to the entire region, the Elves did not hesitate to offer their help to the people of Avalon. With their superior skill as archers, they proved to be the best of their kind and played a crucial role in defeating the Sha\\''Ahoul.

But their abilities are not limited to archery alone. The Elves are also masters of camouflage and stealth, making them fearless fighters in the art of sneaking. In the impenetrable forests, they are nearly invisible and use these skills to ambush their enemies. However, this art of invisibility also hints at their fragility, as they are more vulnerable in direct combat than other races.

Despite their delicacy, the Elves are unwavering in their resolve to protect their homeland and the people of Avalon. Their history is marked by heroic deeds and a willingness to stand up for the good of others. As guardians of the forest and protectors of nature, the Elves embody a timeless wisdom that shines through the centuries, making their people an indispensable part of Avalon\\''s history.','As a member of a race known for its precise archers, you receive 1.5x attack!',0,0,0,0,'a:5:{s:4:"name";s:29:"`2Protector `&of the `@Forest";s:7:"wearoff";s:62:"Racial Power used up. You will regain it on the next game day.";s:6:"rounds";s:2:"10";s:6:"atkmod";s:3:"1.5";s:6:"schema";s:12:"race_creator";}','',0,'','','',NULL),
	 ('Elythria','Demonmegi',1,'Village of Avalon','`2','In your past as a `2Elythria`0, you merge with the noble art of smithing and knighthood, while celebrating your roots in the majestic landscapes and rolling hills of Elythria.','In the land of Elythria, once a flourishing realm nestled between lush hills and ancient forests, thrived a proud and noble people known as the Elythrians. For generations, they had perfected the art of smithing, their skilled hands crafting shining weapons and sturdy armor renowned throughout the land. They were revered knights, guardians of justice and chivalry, whose bravery and courage inspired awe and respect.

But the winds of fate took a dark turn when the evil powers of the Sha\\''Ahoul swept over Eurale. A cataclysmic war erupted, engulfing the once peaceful lands in flames and shadows. The Elythrian forges, once alive with the rhythmic sound of hammers, now lay in ruins, consumed by the fiery wrath of the invading horde.

Amid the chaos, the noble knights of Elythria bravely charged into battle, their swords gleaming like beacons of hope. Yet the enemy showed no mercy, and the once mighty warriors suffered heartbreaking losses. Many of their brothers fell in combat, their heroic spirits forever immortalized in the annals of history.

The craftsmen, the master smiths, once the pride of the realm, now stood amidst the ruins of their craft. The songs of their ancestors, which had passed down their knowledge through the centuries, seemed to fade into the distance as they struggled to rebuild what was lost. The art of smithing, once an expression of their identity, now hung by a thread and threatened to be lost forever.

Beyond the physical devastation, the Elythrians bore the burden of emotional scars. The camaraderie that once bound them inseparably faced a tremendous challenge. The trust that had once been taken for granted among brothers needed healing. The path to reconciliation was arduous, yet the indomitable spirit of the Elythrians endured.

With each dawn, hope flickered amidst the darkness. The Elythrians, a people forged by the flames of adversity, began the first steps on a journey to reclaim their heritage. Slowly but determinedly, they restored the forges and rekindled the fire of their craft by channeling the resolve of their ancestors.

Facing insurmountable obstacles, the Elythrians united, their bond growing stronger with every shared triumph and setback. With every newly forged sword and shining piece of armor, Elythria’s heart beat defiantly onward.

As the sun set over a realm that had weathered the storm of darkness, the Elythrians stood tall, their swords shouldered and spirits rekindled. The legacy of their once-great civilization lived on, etched in the iron they wielded and the knightly virtues they upheld. The echoes of their resilience and honor resonated through the ages, a testament to the unyielding spirit of the Elythrians.','As a member of a skillful and knightly race, you receive 1.5x Defense!',0,0,0,0,'a:5:{s:4:"name";s:24:"`2The Savior `7of Avalon";s:7:"wearoff";s:62:"Racial Power used up. You will regain it on the next game day.";s:6:"rounds";s:2:"10";s:6:"atkmod";s:3:"1.5";s:6:"schema";s:12:"race_creator";}','',0,'','','',NULL),
	 ('Fornax','Demonmegi',1,'Village of Avalon','`)','In your past as a `)Fornax`0, you were part of a mysterious race with unparalleled skills in sorcery, magic, and alchemy. Though feared by rumors, the Fornaxians were highly valued by the inhabitants of Eurale for their exceptional sorcerers and healers.','In the distant lands of the Eurale continent, there exists a race known as the Fornaxians. These mysterious beings master the arts of sorcery, magic, and alchemy in a way that makes them an outstanding and fascinating community. The Fornaxians are not only famous for their magical abilities but also for their aversion to rumors and unnecessary gossip.

Legend has it that the Fornaxians possess the power to manipulate the weather. However, these claims are often disputed, and many doubt their truthfulness. Regardless, the Fornaxians have a reputation as the most mysterious and powerful sorcerers ever to have seen the light of day.

These extraordinary abilities and their aloof nature make the Fornaxians a fascinating yet mistrusted race in the eyes of other peoples on the Eurale continent. Sometimes, there is a certain distance and caution toward the Fornaxians because they are different and wield unknown powers.

Despite occasional mistrust, the inhabitants of the Eurale continent appreciate the Fornaxians for their contributions as gifted sorcerers and healers. The abilities of this enigmatic race are invaluable and have helped many people in need.

The legends and stories about the Fornaxians are numerous, yet their true nature remains shrouded in mist. Their deep knowledge of the arcane arts and their secrets make them a truly fascinating and unique race in the rich lore of the Eurale continent.','As a member of a race known for their skilled mages, you receive 2x attack and +3 regeneration!',0,0,0,0,'a:6:{s:4:"name";s:37:"`)Natural Talent of the `^Arcane Arts";s:7:"wearoff";s:62:"Racial Power used up. You will regain it on the next game day.";s:6:"rounds";s:2:"10";s:6:"atkmod";s:1:"2";s:5:"regen";s:1:"3";s:6:"schema";s:12:"race_creator";}','',0,'','','',NULL);
INSERT INTO lotgd.races (racename,raceauthor,raceactive,racevillage,racecolour,racechoose,raceset,racenewday,raceturns,racetravel,racepvp,racegrave,newdaybuff,pvpadjust,`alter-gemchance`,creatureencounter,`battle-victory`,`battle-defeat`,module) VALUES
	 ('Taberland','Demonmegi',1,'Village of Avalon','`^','In your past as a `^Taberland`0, you belonged to a proud people with an unbeatable heavy cavalry that successfully crushed the armies of the Sha\\''Ahoul during the Siege of Avalon.','The Taberland are a proud people, known for their mighty heavy cavalry that has achieved great success on the battlefield. Their riders, clad in shining armor and armed with heavy swords and lances, are an impressive force that spreads fear and terror among their enemies.

However, the Taberländer were once embroiled in a devastating civil war that threw the land into turmoil. Discord and strife threatened to tear apart their once-strong nation. In this dark time, a young king named Vortigern rose. With wise leadership and determination, he managed to suppress the rebellion and unite the people.

Amidst the united Taberländer, King Vortigern led his powerful heavy cavalry into battle against the armies of the Sha\\''Ahoul. His brave riders were like an unstoppable storm, striking down enemies with bold determination and skilled strategy.

Battle after battle, the Taberländer fought under their young king’s command, and their victorious campaign knew no end. With each victory, their fame grew, and their names were immortalized in the annals of history as heroes of bravery and courage.

Finally, they reached the decisive battle during the Siege of Avalon. With united forces, proud tradition, and the daring of their heavy cavalry, the Taberländer defeated the armies of the Sha\\''Ahoul and freed the land from the dark threat.

The Taberländer are a people whose history is marked by internal conflict and triumphant victories. Their cavalry is not only a symbol of strength and martial skill but also of unity and determination. Their bravery and resolve will live on in the hearts of the people, and their legacy will be enshrined in Avalon’s history books as a shining example of solidarity and overcoming adversity.','As a member of a race that produces the finest heavy cavalry, you receive 2x Attack and 2x Defense!',0,0,0,0,'a:6:{s:4:"name";s:33:"`$King Tortain’s `^Army Tradition";s:7:"wearoff";s:62:"Racial Power used up. You will regain it on the next game day.";s:6:"rounds";s:2:"10";s:6:"atkmod";s:1:"2";s:6:"defmod";s:1:"2";s:6:"schema";s:12:"race_creator";}','',0,'','','',NULL),
	 ('Shamen','Demonmegi',1,'Village of Avalon','`$','In your past as a `4Sha\\''Men`0  of the Sha\\''Ahoul, you were a talented master of elemental magic, a spiritual leader, and a driving force in the Eurale-Sha\\''Ahoul war.','The Sha\\''men of the Sha\\''Ahoul are a remarkable and mysterious group of individuals possessing extraordinary abilities in mastering elemental magic. As masters of the elements, they are the driving force behind the Sha\\''Ahoul’s offensive in the chaos of the Eurale-Sha\\''Ahoul war. Their unparalleled intelligence and tactical skills have earned them the reputation as the spiritual leaders and strategists of the Sha\\''Ahoul army.

During the fierce war, the most famous Sha\\''Men, Shaman Mithras, led the powerful Leopard Clan of the Sha\\''Ahoul as a charismatic leader. It was his exceptional intelligence that enabled him to unite all other clans and forge an unprecedented alliance that stood united against Eurale. Under his wise leadership, the Sha\\''Ahoul became an unstoppable force that transcended the limits of magic and astonished their enemies.

However, the Sha\\''men are more than just powerful wizards; they also embody the essence of wisdom and the source of spiritual knowledge in Sha\\''Ahoul culture. Rooted in the ancient teachings and secrets of their craft, they serve as spiritual guides for their clans and advisors to the Sha\\''Ahoul leader. Their deep understanding of nature and the elements allows them not only to wield destructive magic but also healing powers that can save the lives of their comrades and strengthen their allies.

As guardians of the balance between the forces of nature and the destinies of the Sha\\''Ahoul, the Sha\\''men are able to control and channel the immense power of the elements. Their connection to the environment enables them to merge with nature and become almost invisible in the forests of Eurale. In battle, they unleash the power of fire, water, earth, and air to defeat their enemies and lead the Sha\\''Ahoul army to victory.

Thus, the Sha\\''men of the Sha\\''Ahoul are not only powerful sorcerers and spiritual leaders but also the living embodiment of Sha\\''Ahoul culture and the pride of their people. Their contribution to the Eurale-Sha\\''Ahoul war was invaluable, and their legacy will live on as heroes in the legends and stories of the Sha\\''Ahoul for all time.','As a member of an offensive race known for its extremely powerful elemental mages, you receive 2x attack and 25% of the damage taken is reflected back to the enemy!',0,0,0,0,'a:6:{s:4:"name";s:30:"`$The Firewalker `1of the East";s:7:"wearoff";s:62:"Racial Power used up. You will regain it on the next game day.";s:6:"rounds";s:2:"10";s:6:"atkmod";s:1:"2";s:7:"lifetap";s:4:"1.25";s:6:"schema";s:12:"race_creator";}','',0,'','','',NULL),
	 ('Lich','Demonmegi',1,'Village of Avalon','`5','In your past as a `~Lich0, you made a pact with darkness by giving up your mortal body and guarding your soul in the Lichstone.','The Liches are scholars of death and decay, mastering the art of summoning undead creatures. These abilities make you a feared opponent and a powerful ally. But caution is necessary, for darkness comes at a price. As a Lich, you are not immune to the temptations of darkness and must constantly fight to avoid being consumed by it.

The Lichstone you carry holds a deep secret—it contains your soul, which you guard with utmost devotion. This soul is the source of your power and immortality, and you are determined to protect it from any threat.

The bond between you and the Lichstone is unbreakable, and you are inseparably connected. Your soul is trapped within the stone, and you guard it with iron will. This grants you not only extraordinary powers but also a unique responsibility.

Guarding your soul within the Lichstone is a central part of your lich existence and identity. The darkness surrounding you is not only external but also internal. The choice to preserve your soul in the Lichstone comes at a high price, and you are constantly confronted with resisting the temptations of darkness and preserving your own identity.

Your decision to become a Lich and safeguard your soul in the Lichstone influences the world around you and shapes your interactions with other characters. Are you ready to bear this heavy burden and keep the secrets of the Lichstone? Welcome to the world of Liches, where darkness, death, and the relentless guarding of your own soul are your constant companions.','As a member of a race known for its immortality, you are immortal, but you must constantly protect your Lichstone, which causes you to have -6 Forest Battles!',-6,0,0,0,'a:5:{s:4:"name";s:23:"`~Eternal `5Necromancer";s:7:"wearoff";s:62:"Racial Power used up. You will regain it on the next game day.";s:6:"rounds";s:5:"65000";s:12:"invulnerable";s:1:"1";s:6:"schema";s:12:"race_creator";}','',0,'','','',NULL),
	 ('Vampire','Demonmegi',0,'Village of Avalon','`4','In your dark past, you forged a pact with the darkness by abandoning your human existence and anchoring your soul within the shadowy halls of the vampires.','In the shadowy depths of the supernatural world dwells the vampire race, their existence shrouded in darkness, mystery, and an insatiable thirst for power. These immortal beings possess incredibly enhanced abilities and are known as masters of secret magic, having forged a legacy that spans countless centuries.

Generations of Vampires:

Vampires are organized into generations, a hierarchical system that determines their strength and potency. The rule is simple: the higher the generation number, the weaker the vampire.

First Generation:
First-generation vampires stand at the pinnacle of vampiric power. These ancient creatures are the forebears of their kind and possess abilities bordering on divine, making them nearly invincible. Their mastery of magic is unparalleled, allowing them to manipulate reality itself. Legends speak of their power to control the elements and command legions of lesser vampires.

Second Generation:
Descended from the first generation, second-generation vampires remain formidable in their own right. Their strength surpasses most supernatural beings, and they wield impressive magical powers. Though not as all-powerful as their ancestors, they are feared and respected throughout the vampire world.

Third Generation:
Bitten by a second-generation vampire, the third generation represents the majority of the vampire population. They possess many typical vampire abilities: heightened senses, incredible speed and strength, and an affinity for magic. While not as powerful as their predecessors, their potential is vast, and they continue to grow stronger as they age.','As a member of a race known for its unmatched magical power and as extremely powerful undead among the living, you receive the following bonuses:
+4 Regeneration
+4 Life Drain
+3 Attack
+3 Defense

However, due to your vulnerability to daylight, you lose -3 rounds in battles!',-3,0,0,0,'a:8:{s:4:"name";s:35:"`4Overlord from the `4Crimson Realm";s:7:"wearoff";s:62:"Racial Power used up. You will regain it on the next game day.";s:6:"rounds";s:2:"20";s:6:"atkmod";s:1:"3";s:6:"defmod";s:1:"3";s:5:"regen";s:1:"4";s:7:"lifetap";s:1:"4";s:6:"schema";s:12:"race_creator";}','',0,'','','',NULL);
